from .interactive_idino_m2m import interactive_infer_image as interactive_infer_image_idino_m2m
from .interactive_idino_m2m_auto import interactive_infer_image as interactive_infer_image_idino_m2m_auto
from .interactive_idino_m2m_auto import interactive_infer_image_multilevel as interactive_infer_image_idino_m2m_auto_multilevel
from .automatic_mask_generator import prompt_switch
from .interactive_predictor import SemanticSAMPredictor
